spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/librarydb
    username: postgres
    password: Luc@s1122!
    driver-class-name: org.postgresql.Driver
